name: hack

on:
  schedule:
    # 使用cron表达式来设置定时任务，这个例子是在每天的中午12点运行
    - cron: '30 0,5,10,15,20 * * *'
  workflow_dispatch:
    #手动触发      

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout 仓库代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # 这里可以指定 Python 版本，比如 3.9

    # 安装项目的依赖项（如果有）
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果有 requirements.txt 文件，取消下一行注释
         pip install -r requirements.txt

    # 运行你的 fofa.py 文件
    - name: Run Python script
      run: |
        python3 fofa.py -k '(protocol=="socks5" && region="HK") && after="2025-04-30" && port="1080"' --outputname socks --endcount 25
    # 运行 list.py 文件
    - name: Run list.py
      run: |
        python3 listquchong.py socks.txt
    # 移动生成的 socks.txt 文件到 fancy 目录
    - name: Move socks.txt to fancy directory
      run: |
        mv socks.txt fancy/    
    #运行   
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f fancy/socks.txt
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Add socks.txt'
          git push
        fi
